spring:
  datasource:
    username: sa
    password: sa
    url: "jdbc:h2:mem:coredata;DB_CLOSE_ON_EXIT=FALSE;MODE=MySQL;DB_CLOSE_DELAY=-1"
    driverClassName: org.h2.Driver
  batch:
    job:
      enabled: false